spring:
    application:
            name: aiservice
    data:
        mongodb:
            uri: mongodb://localhost:27017/airecommendationfitness
            database: airecommendationfitness
            auto-index-creation: true
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: activity-processor-group
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.use.type.headers: false
                spring.json.trusted.packages: '*'
                spring.json.value.default.type: com.fitness.aiservice.model.Activity


gemini:
    api:
        url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
        key: AIzaSyDSQrQJA3oaddWJcMBEnZS45O8LHhG6Dxk
        
kafka:    
  topic:
    name: activity-events          



eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true

server:
    port: 8083





